name: CD-GCR

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: docker build . -t gcr.io/$GCLOUD_PROJECT/accessmanagerv3:$GITHUB_SHA

      - name: Push Docker image
        run: docker push gcr.io/$GCLOUD_PROJECT/accessmanagerv3:$GITHUB_SHA