name: Sleep for 5 minutes

on:
  workflow_dispatch:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  sleep:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f1db3319d7db49c70352da1f5d1a122f754e8c01 # int
      with:
        egress-policy: audit

    - name: Wait for 5 minutes
      run: sleep 300
